# Generated by Django 5.0.3 on 2025-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ssr_primers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=200)),
                ('standard', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=50)),
                ('repeat', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('clade', models.IntegerField()),
                ('subclade', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=300)),
                ('forward', models.CharField(max_length=200)),
                ('tm_forward', models.FloatField()),
                ('gc_forward', models.FloatField()),
                ('stability_forward', models.FloatField()),
                ('reverse', models.CharField(max_length=200)),
                ('tm_reverse', models.FloatField()),
                ('gc_reverse', models.FloatField()),
                ('stability_reverse', models.FloatField()),
            ],
        ),
    ]
